### ISSUE TITLE
Require packages in a thread

### ISSUE THREAD

**Issue by biziosan** [MKGaru/thread.js#1]
Hi,

First of all, I really like your library! It's simple and hides lots of things.

I am new to threads in Typescript, so this might be very simple. Is there a way to require local packages inside the thread? I see you have example 6 with a link to a library but I am looking for local packages in the `node_modules`. Example: I use MongoDB to manage collections of big files. I would like to access to the DB from inside the thread requiring the `mongodb` package (or any other package we use in our application) with a `const MongoDB = require('mongodb')`.

Thank you!

**Comment by MKGaru** [comment]
Hi.

MongoDB ? 
You want use on nodejs? 
I think WebWorker is design for browser.

Thanks.

**Comment by MKGaru** [comment]
I added example , and experimental support nodejs.
